apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testnodejs 
  janus-idp.io/tekton: testnodejs
  backstage.io/kubernetes-id: testnodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testnodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  