apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testnodejs-gitops
  description: This is GitOps manifest for testnodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testnodejs
    janus-idp.io/tekton: testnodejs 
    backstage.io/kubernetes-id: testnodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testnodejs
